package Lair::Controller::Favicon;

use Lair::Ground;
use Lair::Resource;
use Badger::Codec::Base64;

use Badger::Class
    version => '0.01',
    base => 'Lair::Controller',
    mutators => [
        'favicon'
    ];

sub _default_prefix { '/favicon.ico' }

sub _default_resources
{[
  Lair::Resource->new(regex => qr||,
    get => sub {
        my ($self,$response) = @_;
        $response->header('Last-Modified','Thu, 23 Feb 2012 17:44:49 GMT');
        return $self->controller->favicon
    },
    returns => 'image/x-icon')
]}

sub _default_favicon {
  return Badger::Codec::Base64->decode(
'AAABAAEAEBAAAAEACABoBQAAFgAAACgAAAAQAAAAIAAAAAEACAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAABAAAAAgAAAAMAAAAEAAAABQAAAQQAAAAIAAACAgAAAAsAAAAOAAAAEAAAABEA
AAAUAAAFBAAAABUAAAMLAAAECQAAABcAAAAaAAAAHAAABA8AAAAdAAAAHwAAAxYAAAAjAAAAJgAA
ACcAAAApAAAALAAAAC0AAAAuAAAALwAAADEAAAoQAAkKDwAACRYAAAgaAAAANQAAADcAAAsUAAAI
IAA4CwQAAAA+AAAAQAAACCgAKw0JAAAARwAAAEoAAABLACMPDQAAAE0AAABWAAAAVwAAAFgAAABZ
ABQTFAAAECYAAABeAAAUHQAAFRoAAABkAAAAZQAAAGcAABccAAATKwABCFAAAABuAAAAbwAAAHAA
AA1GAAIHWgAAAHQABAZhAAAAdwAAAHkAAA1OAAAaIwAAAHsAAA9JAAAAfAAAEEcAAAB9AAAPSwAA
AH8AAA9NAAAAgAAICGQAJRwXAAAAggABCGcAAACDAAAAhQAAAIcAAACJAAAAjAABFkIAAACNAAAW
QwAFB3QAAACOAAAMZgATHyAAACEjAAAAkwAAGEMAAAGRAAcAkgAAAJgAAACdABwjHwADDXIAAACf
AAQcQAAAAKQAAASYABMmIQAAAKkACQuBAAAAqwAAAK0AACgnAAABrQAABKMAAAKsAAcHmQAXKSMA
AQedAAALkQAEB6YAAADBAAAJowAAArsAFCwpAAAHrQAACKsAGhN/AAAIrQAADZ4AAAmvAAAA0QAA
C7AAAA2qABoRmwAJE5wAJBKhAAAPvQAAEbgAABavAAA4QQAAHZ0AABukAAAgnQAAIZwAACGjADMi
kgASJZkALCKhAAAW3AAAJrgAACLLAAAyogAAOaYAADisAAwuzAAAOqkAAD+xAABAvAAASKQAAEav
AAJEuwAATakAGUDOAABKuQAAUbAAAFOyAABPxQAAV7cAAFm3AABfsAAAXrYAA2C5AABkuwAFX9AA
AGi8AABuxAAAccEAAHi9ABN1yQAAe8IAAIPDAACD0QAAic4AAIvIAACNzAANi9IAAI7PAACRzgAA
lNMAAJzXAACm2QAAq9kAAKvcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAARyEcGhobAAAAABlGUU9TVVcnHRoaAAAAAAAUFHFgYmljSQQBBQA5BAMAEgwYExIPWkIXKU0A
EAAIeTguMiMkJWVMEgo7PCJmdH5uhVgqZy1vKwAAAABABgAAEZUVDigJiDQvLAQFHEELDQACABcW
Ep1bRTo1HjAxAgcNCwkgJh9rgXteS0N2PT8zICcmNj6cUnKCkmxWUFRbRDc+aGyGg114jJ6CcF9c
Sl1OXHqJbWR9h4Sgk45QSlBZSESKYWqAm49/c5iXlIt1X19hmqKutJGQmaGxraefjXd8qqayur2k
sLnFwrivpZajqba6wMbKrLe/xMG+u7Ooq7W8w8fIyQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=')
}

1;

__END__

=head1 NAME

Lair::Controller::Favicon - a default favicon controller

=head1 SYNOPSIS

   use Plack::Builder;
   use Lair;
   use Lair::Controller::Favicon;

   my $app = Lair->new('name' => 'show lair favicon');
   builder { $app->add_controller( Lair::Controller::Favicon->new )->handler }

head1 DESCRIPTION

